name: "Process Release Notes"
description: "Processes release notes for Play Store in multiple languages"

inputs:
  release-notes:
    description: "Release notes: plain text for en-US, or XML-like tags for multiple languages: <en-US>text</en-US><es-ES>texto</es-ES>"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create release notes files
      shell: bash
      run: |
        mkdir -p whatsnew

        NOTES='${{ inputs.release-notes }}'

        # Check if input contains language tags like <en-US>...</en-US>
        if echo "$NOTES" | grep -qE '<[a-z]{2}-[A-Z]{2}>'; then
          echo "Processing multilingual release notes (XML-like format)..."

          # Extract each language tag and create corresponding files
          # Use perl for better regex support with multiline matching
          echo "$NOTES" | perl -0777 -ne '
            while (/<([a-z]{2}-[A-Z]{2})>(.*?)<\/\1>/gs) {
              my $locale = $1;
              my $content = $2;

              # Trim leading and trailing whitespace (including newlines)
              $content =~ s/^\s+|\s+$//g;

              # Write to file if content is not empty
              if ($content ne "") {
                open(my $fh, ">", "whatsnew/whatsnew-$locale") or die "Cannot write file: $!";
                print $fh $content;
                close($fh);
                print "✓ Created whatsnew-$locale\n";
              }
            }
          '

          echo ""
          echo "Release notes created for languages:"
          ls -1 whatsnew/
        else
          echo "Processing single language release notes (plain text)..."
          # Trim leading and trailing whitespace for plain text too
          echo "$NOTES" | perl -pe 's/^\s+|\s+$//g' > whatsnew/whatsnew-en-US
          echo "✓ Created whatsnew-en-US"
        fi

        echo ""
        echo "Release notes contents:"
        for file in whatsnew/*; do
          echo "--- $(basename $file) ---"
          cat "$file"
          echo ""
        done
