name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Configuration Variables (Optional)
# To customize versions, set these in: Settings → Secrets and variables → Actions → Variables
#
# Available variables:
#   - FLUTTER_VERSION: Flutter SDK version (default: 3.35.x)
#   - JAVA_VERSION: Java JDK version (default: 17)

jobs:
  analyze:
    name: Analyze & Format Check & Test
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ vars.JAVA_VERSION || '17' }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ vars.FLUTTER_VERSION || '3.35.x' }}
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'

      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.PUB_CACHE }}
            ~/.pub-cache
            ${{ github.workspace }}/.dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      - name: Verify Flutter installation
        run: flutter doctor -v

      - name: Check format
        run: dart format --set-exit-if-changed .

      - name: Analyze code
        run: flutter analyze --fatal-infos

      - name: Run tests
        run: echo "No tests available yet"
        # run: flutter test --coverage

  # build-android:
  #   name: Build Android APK (Release)
  #   runs-on: ubuntu-24.04
  #   timeout-minutes: 30
  #   needs: analyze

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Flutter Environment
  #       uses: ./.github/actions/setup-flutter
  #       with:
  #         java-version: ${{ vars.JAVA_VERSION || '17' }}
  #         flutter-version: ${{ vars.FLUTTER_VERSION || '3.35.x' }}

  #     - name: Build Android
  #       uses: ./.github/actions/build-android
  #       with:
  #         build-type: apk
  #         build-mode: release
  #         keystore-base64: ${{ vars.ANDROID_KEYSTORE_BASE64 }}
  #         key-properties: ${{ vars.ANDROID_KEY_PROPERTIES }}

  #     - name: Upload Release APK artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: android-release-apk-${{ github.run_number }}-${{ github.sha }}
  #         path: build/app/outputs/flutter-apk/app-release.apk
  #         retention-days: 7

  # build-ios:
  #   name: Build iOS (No Signing)
  #   runs-on: macos-15
  #   timeout-minutes: 30
  #   needs: analyze

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: ${{ vars.FLUTTER_VERSION || '3.35.x' }}
  #         channel: 'stable'
  #         cache: true
  #         cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
  #         cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'

  #     - name: Cache pub dependencies
  #       uses: actions/cache@v4
  #       with:
  #         path: |
  #           ${{ env.PUB_CACHE }}
  #           ~/.pub-cache
  #           ${{ github.workspace }}/.dart_tool
  #         key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-pub-

  #     - name: Cache CocoaPods
  #       uses: actions/cache@v4
  #       with:
  #         path: |
  #           ios/Pods
  #           ~/Library/Caches/CocoaPods
  #           ~/.cocoapods
  #         key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-pods-

  #     - name: Install dependencies
  #       run: flutter pub get

  #     - name: Run code generation
  #       run: dart run build_runner build --delete-conflicting-outputs

  #     - name: Install CocoaPods dependencies
  #       run: |
  #         cd ios
  #         pod install
  #         cd ..

  #     - name: Build iOS (no codesign)
  #       run: flutter build ios --release --no-codesign

  #     - name: Build info
  #       run: |
  #         echo "::notice::iOS build completed without code signing"
  #         echo "::notice::For signed builds, configure signing certificates and profiles"
