name: Publish to Play Store
run-name: Publish to ${{ inputs.track }} track

on:
  workflow_dispatch:
    inputs:
      build_run_url:
        description: "GitHub Actions run URL from manual-build workflow (e.g., https://github.com/owner/repo/actions/runs/123456)"
        required: true
        type: string

      track:
        description: "Play Store track to publish to"
        required: true
        type: choice
        default: "internal"
        options:
          - "internal"
          - "alpha"
          - "beta"
          - "production"

      rollout_percentage:
        description: "Staged rollout percentage (production only, 5-100)"
        required: false
        type: string
        default: "100"

      release_notes:
        description: 'Release notes: plain text for en-US, or XML-like tags for multiple languages: <en-US>text</en-US><es-ES>texto</es-ES>'
        required: false
        type: string

      in_app_update_priority:
        description: "In-app update priority (0-5, higher = more urgent)"
        required: false
        type: choice
        default: "2"
        options:
          - "0"
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"

# Configuration Secrets (Required)
# To publish to Play Store, set these in: Settings → Secrets and variables → Actions → Secrets
#
# Required secrets:
#   - PLAY_STORE_SERVICE_ACCOUNT: Service account JSON from Google Play Console
#   - PLAY_STORE_PACKAGE_NAME: Your app's package name (e.g., com.example.app)

# Workflow permissions required for cross-run artifact access
permissions:
  actions: read    # Required to access workflow run data and download artifacts from other runs
  contents: read   # Required to checkout repository for custom actions

jobs:
  parse-input:
    name: Parse Build Run URL
    runs-on: ubuntu-24.04
    outputs:
      run_id: ${{ steps.parse.outputs.run_id }}
      repository: ${{ steps.parse.outputs.repository }}

    steps:
      - name: Extract run ID and repository from URL
        id: parse
        run: |
          URL="${{ inputs.build_run_url }}"

          # Extract repository and run ID from URL
          # Format: https://github.com/owner/repo/actions/runs/12345
          if [[ "$URL" =~ github\.com/([^/]+/[^/]+)/actions/runs/([0-9]+) ]]; then
            REPO="${BASH_REMATCH[1]}"
            RUN_ID="${BASH_REMATCH[2]}"
            echo "repository=$REPO" >> $GITHUB_OUTPUT
            echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
            echo "✓ Extracted repository: $REPO"
            echo "✓ Extracted run ID: $RUN_ID"
          else
            echo "::error::Invalid GitHub Actions run URL format"
            echo "::error::Expected format: https://github.com/owner/repo/actions/runs/123456"
            echo "::error::Provided: $URL"
            exit 1
          fi

  validate:
    name: Validate Inputs
    runs-on: ubuntu-24.04
    needs: parse-input

    steps:
      - name: Checkout for actions
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/actions

      - name: Validate rollout percentage
        if: inputs.track == 'production'
        run: |
          PERCENTAGE="${{ inputs.rollout_percentage }}"

          if [[ ! "$PERCENTAGE" =~ ^[0-9]+$ ]]; then
            echo "::error::Rollout percentage must be a number"
            exit 1
          fi

          if [ "$PERCENTAGE" -lt 5 ] || [ "$PERCENTAGE" -gt 100 ]; then
            echo "::error::Rollout percentage must be between 5 and 100"
            exit 1
          fi

          echo "✓ Rollout percentage validation passed: ${PERCENTAGE}%"

      - name: Validate Play Store secrets
        uses: ./.github/actions/validate-playstore-secrets
        with:
          service-account: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT }}
          package-name: ${{ secrets.PLAY_STORE_PACKAGE_NAME }}

  download-artifact:
    name: Download App Bundle
    runs-on: ubuntu-24.04
    needs: [parse-input, validate]
    outputs:
      artifact_name: ${{ steps.find-bundle.outputs.artifact_name }}

    steps:
      - name: Download artifacts from build run using GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RUN_ID="${{ needs.parse-input.outputs.run_id }}"
          REPO="${{ needs.parse-input.outputs.repository }}"

          echo "Listing artifacts from run $RUN_ID in repository $REPO..."
          gh run view "$RUN_ID" --repo "$REPO"

          echo ""
          echo "Available artifacts:"
          gh run view "$RUN_ID" --repo "$REPO" --json artifacts --jq '.artifacts[] | "\(.name)"'

          echo ""
          echo "Downloading artifacts..."
          gh run download "$RUN_ID" --repo "$REPO" --dir ./artifacts

      - name: Find bundle-release artifact
        id: find-bundle
        run: |
          echo "Downloaded artifacts:"
          ls -la ./artifacts/

          # Find the bundle-release artifact directory
          BUNDLE_DIR=$(find ./artifacts -type d -name "*-bundle-release-*" | head -n 1)

          if [ -z "$BUNDLE_DIR" ]; then
            echo "::error::No bundle-release artifact found in the build run"
            echo "::error::Available artifacts:"
            ls -la ./artifacts/
            exit 1
          fi

          ARTIFACT_NAME=$(basename "$BUNDLE_DIR")
          echo "artifact_name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT
          echo "✓ Found bundle artifact: $ARTIFACT_NAME"

          # Move the bundle to expected location
          mkdir -p ./aab
          mv "$BUNDLE_DIR"/* ./aab/
          echo "✓ Moved bundle to ./aab/"

      - name: Verify AAB exists
        run: |
          echo "Contents of downloaded artifact:"
          ls -lah ./aab/

          # Find the AAB file (might be app-release.aab or nested)
          AAB_FILE=$(find ./aab -name "*.aab" -type f | head -n 1)

          if [ -z "$AAB_FILE" ]; then
            echo "::error::No .aab file found in artifact!"
            echo "::error::Make sure the artifact contains a release app bundle"
            exit 1
          fi

          echo "Found AAB file: $AAB_FILE"
          AAB_SIZE=$(stat -c%s "$AAB_FILE")
          echo "✓ AAB file size: ${AAB_SIZE} bytes"

          # Move to standard location if needed
          if [ "$AAB_FILE" != "./aab/app-release.aab" ]; then
            mv "$AAB_FILE" ./aab/app-release.aab
            echo "Moved to ./aab/app-release.aab"
          fi

      - name: Upload AAB for publishing
        uses: actions/upload-artifact@v4
        with:
          name: ready-to-publish-${{ github.run_number }}
          path: ./aab/app-release.aab
          retention-days: 1

  publish:
    name: Publish to ${{ inputs.track }} Track
    runs-on: ubuntu-24.04
    needs: download-artifact
    timeout-minutes: 15

    steps:
      - name: Checkout for actions
        if: inputs.release_notes != ''
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/actions

      - name: Download AAB
        uses: actions/download-artifact@v4
        with:
          name: ready-to-publish-${{ github.run_number }}
          path: ./

      - name: Process release notes
        if: inputs.release_notes != ''
        uses: ./.github/actions/process-release-notes
        with:
          release-notes: ${{ inputs.release_notes }}

      - name: Publish to Play Store (${{ inputs.track }} track)
        uses: ./.github/actions/publish-playstore
        with:
          service-account-json: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT }}
          package-name: ${{ secrets.PLAY_STORE_PACKAGE_NAME }}
          release-files: app-release.aab
          track: ${{ inputs.track }}
          status: completed
          in-app-update-priority: ${{ inputs.in_app_update_priority }}
          rollout-percentage: ${{ inputs.track == 'production' && inputs.rollout_percentage || '' }}
          whats-new-directory: ${{ inputs.release_notes != '' && 'whatsnew' || '' }}

      - name: Publishing summary
        if: success()
        run: |
          echo "## ✓ Successfully Published to Play Store" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Track:** ${{ inputs.track }}" >> $GITHUB_STEP_SUMMARY
          echo "**Artifact:** \`${{ needs.download-artifact.outputs.artifact_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Build Run:** ${{ inputs.build_run_url }}" >> $GITHUB_STEP_SUMMARY

          if [ "${{ inputs.track }}" == "production" ]; then
            echo "**Rollout:** ${{ inputs.rollout_percentage }}%" >> $GITHUB_STEP_SUMMARY
          fi

          echo "**In-App Update Priority:** ${{ inputs.in_app_update_priority }}" >> $GITHUB_STEP_SUMMARY

          if [ -n "${{ inputs.release_notes }}" ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Release Notes:**" >> $GITHUB_STEP_SUMMARY
            echo "${{ inputs.release_notes }}" >> $GITHUB_STEP_SUMMARY
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "🎉 Your app is now live on the **${{ inputs.track }}** track!" >> $GITHUB_STEP_SUMMARY

      - name: Publishing failed
        if: failure()
        run: |
          echo "## ✗ Publishing Failed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Track:** ${{ inputs.track }}" >> $GITHUB_STEP_SUMMARY
          echo "**Build Run:** ${{ inputs.build_run_url }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Please check the logs above for error details." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Common issues:" >> $GITHUB_STEP_SUMMARY
          echo "- Invalid service account credentials" >> $GITHUB_STEP_SUMMARY
          echo "- Version code already exists on this track" >> $GITHUB_STEP_SUMMARY
          echo "- Package name mismatch" >> $GITHUB_STEP_SUMMARY
          echo "- Insufficient permissions for service account" >> $GITHUB_STEP_SUMMARY
