name: Publish to Play Store
run-name: Publish to ${{ inputs.track }} track${{ inputs.artifact_name && format(' - {0}', inputs.artifact_name) || '' }}

on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: "Artifact name from manual-build workflow (e.g., myapp-1.0.0-manual-build-bundle-release-123-abc1234)"
        required: true
        type: string

      track:
        description: "Play Store track to publish to"
        required: true
        type: choice
        default: "internal"
        options:
          - "internal"
          - "alpha"
          - "beta"
          - "production"

      rollout_percentage:
        description: "Staged rollout percentage (production only, 5-100)"
        required: false
        type: string
        default: "100"

      release_notes:
        description: 'Release notes: plain text for en-US, or XML-like tags for multiple languages: <en-US>text</en-US><es-ES>texto</es-ES>'
        required: false
        type: string

      in_app_update_priority:
        description: "In-app update priority (0-5, higher = more urgent)"
        required: false
        type: choice
        default: "2"
        options:
          - "0"
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"

# Configuration Secrets (Required)
# To publish to Play Store, set these in: Settings → Secrets and variables → Actions → Secrets
#
# Required secrets:
#   - PLAY_STORE_SERVICE_ACCOUNT: Service account JSON from Google Play Console
#   - PLAY_STORE_PACKAGE_NAME: Your app's package name (e.g., com.example.app)

jobs:
  validate:
    name: Validate Inputs
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout for actions
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/actions

      - name: Validate artifact name
        run: |
          ARTIFACT="${{ inputs.artifact_name }}"

          # Check if artifact name contains "bundle-release"
          if [[ ! "$ARTIFACT" =~ bundle-release ]]; then
            echo "::error::Artifact name must be for a release app bundle (should contain 'bundle-release')"
            echo "::error::Provided: $ARTIFACT"
            exit 1
          fi

          echo "✓ Artifact name validation passed"

      - name: Validate rollout percentage
        if: inputs.track == 'production'
        run: |
          PERCENTAGE="${{ inputs.rollout_percentage }}"

          if [[ ! "$PERCENTAGE" =~ ^[0-9]+$ ]]; then
            echo "::error::Rollout percentage must be a number"
            exit 1
          fi

          if [ "$PERCENTAGE" -lt 5 ] || [ "$PERCENTAGE" -gt 100 ]; then
            echo "::error::Rollout percentage must be between 5 and 100"
            exit 1
          fi

          echo "✓ Rollout percentage validation passed: ${PERCENTAGE}%"

      - name: Validate Play Store secrets
        uses: ./.github/actions/validate-playstore-secrets
        with:
          service-account: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT }}
          package-name: ${{ secrets.PLAY_STORE_PACKAGE_NAME }}

  download-artifact:
    name: Download App Bundle
    runs-on: ubuntu-24.04
    needs: validate

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ./aab

      - name: Verify AAB exists
        run: |
          echo "Contents of downloaded artifact:"
          ls -lah ./aab/

          # Find the AAB file (might be app-release.aab or nested)
          AAB_FILE=$(find ./aab -name "*.aab" -type f | head -n 1)

          if [ -z "$AAB_FILE" ]; then
            echo "::error::No .aab file found in artifact!"
            echo "::error::Make sure the artifact contains a release app bundle"
            exit 1
          fi

          echo "Found AAB file: $AAB_FILE"
          AAB_SIZE=$(stat -c%s "$AAB_FILE")
          echo "✓ AAB file size: ${AAB_SIZE} bytes"

          # Move to standard location if needed
          if [ "$AAB_FILE" != "./aab/app-release.aab" ]; then
            mv "$AAB_FILE" ./aab/app-release.aab
            echo "Moved to ./aab/app-release.aab"
          fi

      - name: Upload AAB for publishing
        uses: actions/upload-artifact@v4
        with:
          name: ready-to-publish-${{ github.run_number }}
          path: ./aab/app-release.aab
          retention-days: 1

  publish:
    name: Publish to ${{ inputs.track }} Track
    runs-on: ubuntu-24.04
    needs: download-artifact
    timeout-minutes: 15

    steps:
      - name: Checkout for actions
        if: inputs.release_notes != ''
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/actions

      - name: Download AAB
        uses: actions/download-artifact@v4
        with:
          name: ready-to-publish-${{ github.run_number }}
          path: ./

      - name: Process release notes
        if: inputs.release_notes != ''
        uses: ./.github/actions/process-release-notes
        with:
          release-notes: ${{ inputs.release_notes }}

      - name: Publish to Play Store (${{ inputs.track }} track)
        uses: ./.github/actions/publish-playstore
        with:
          service-account-json: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT }}
          package-name: ${{ secrets.PLAY_STORE_PACKAGE_NAME }}
          release-files: app-release.aab
          track: ${{ inputs.track }}
          status: completed
          in-app-update-priority: ${{ inputs.in_app_update_priority }}
          rollout-percentage: ${{ inputs.track == 'production' && inputs.rollout_percentage || '' }}
          whats-new-directory: ${{ inputs.release_notes != '' && 'whatsnew' || '' }}

      - name: Publishing summary
        if: success()
        run: |
          echo "## ✓ Successfully Published to Play Store" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Track:** ${{ inputs.track }}" >> $GITHUB_STEP_SUMMARY
          echo "**Artifact:** \`${{ inputs.artifact_name }}\`" >> $GITHUB_STEP_SUMMARY

          if [ "${{ inputs.track }}" == "production" ]; then
            echo "**Rollout:** ${{ inputs.rollout_percentage }}%" >> $GITHUB_STEP_SUMMARY
          fi

          echo "**In-App Update Priority:** ${{ inputs.in_app_update_priority }}" >> $GITHUB_STEP_SUMMARY

          if [ -n "${{ inputs.release_notes }}" ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Release Notes:**" >> $GITHUB_STEP_SUMMARY
            echo "${{ inputs.release_notes }}" >> $GITHUB_STEP_SUMMARY
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "🎉 Your app is now live on the **${{ inputs.track }}** track!" >> $GITHUB_STEP_SUMMARY

      - name: Publishing failed
        if: failure()
        run: |
          echo "## ✗ Publishing Failed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Track:** ${{ inputs.track }}" >> $GITHUB_STEP_SUMMARY
          echo "**Artifact:** \`${{ inputs.artifact_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Please check the logs above for error details." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Common issues:" >> $GITHUB_STEP_SUMMARY
          echo "- Invalid service account credentials" >> $GITHUB_STEP_SUMMARY
          echo "- Version code already exists on this track" >> $GITHUB_STEP_SUMMARY
          echo "- Package name mismatch" >> $GITHUB_STEP_SUMMARY
          echo "- Insufficient permissions for service account" >> $GITHUB_STEP_SUMMARY
